CREATE DATABASE IF NOT EXISTS billing_app
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE billing_app;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  sku VARCHAR(80) NOT NULL UNIQUE,
  hsn VARCHAR(40) NOT NULL,
  description TEXT NOT NULL,
  purchase_price DECIMAL(12, 2) NOT NULL DEFAULT 0,
  selling_price DECIMAL(12, 2) NOT NULL DEFAULT 0,
  gst_rate DECIMAL(5, 2) NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(254) NOT NULL DEFAULT '',
  phone VARCHAR(40) NOT NULL DEFAULT '',
  company_name VARCHAR(180) NOT NULL DEFAULT '',
  gstin VARCHAR(20) NOT NULL DEFAULT '',
  address TEXT NOT NULL,
  state VARCHAR(100) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  invoice_number VARCHAR(40) NOT NULL UNIQUE,
  customer_id BIGINT UNSIGNED NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE NULL,
  notes TEXT NOT NULL,
  subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  discount_type VARCHAR(10) NOT NULL DEFAULT 'amount',
  discount_value DECIMAL(12, 2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'Draft',
  tax_type VARCHAR(8) NOT NULL DEFAULT 'unknown',
  seller_snapshot JSON NULL,
  customer_snapshot JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_invoices_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE IF NOT EXISTS invoice_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  invoice_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NULL,
  product_name VARCHAR(160) NOT NULL,
  sku VARCHAR(80) NOT NULL DEFAULT '',
  hsn VARCHAR(40) NOT NULL DEFAULT '',
  description TEXT NULL,
  quantity DECIMAL(12, 2) NOT NULL,
  unit_price DECIMAL(12, 2) NOT NULL,
  gst_rate DECIMAL(5, 2) NOT NULL,
  line_subtotal DECIMAL(12, 2) NOT NULL,
  line_tax DECIMAL(12, 2) NOT NULL,
  cgst_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  sgst_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  igst_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
  CONSTRAINT fk_invoice_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS invoice_assets (
  invoice_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  digital_seal MEDIUMTEXT NOT NULL,
  digital_signature MEDIUMTEXT NOT NULL,
  CONSTRAINT fk_invoice_assets_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS company_details (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  company_name VARCHAR(180) NOT NULL DEFAULT '',
  gstin VARCHAR(20) NOT NULL DEFAULT '',
  pan VARCHAR(10) NOT NULL DEFAULT '',
  email VARCHAR(254) NOT NULL DEFAULT '',
  phone VARCHAR(40) NOT NULL DEFAULT '',
  website VARCHAR(255) NOT NULL DEFAULT '',
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL DEFAULT '',
  state VARCHAR(100) NOT NULL DEFAULT '',
  postal_code VARCHAR(20) NOT NULL DEFAULT '',
  bank_name VARCHAR(160) NOT NULL DEFAULT '',
  account_holder_name VARCHAR(180) NOT NULL DEFAULT '',
  account_number VARCHAR(80) NOT NULL DEFAULT '',
  account_type VARCHAR(40) NOT NULL DEFAULT '',
  ifsc_code VARCHAR(20) NOT NULL DEFAULT '',
  bank_branch VARCHAR(160) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
